# Lesson: Omarchy Read-Only Familiarization
# AI learns Omarchy OS configuration structure safely

lesson: 'Omarchy Read-Only Familiarization'
version: '1.0'
author: 'Speccy-Kit Training Lab'
stage: 'observer' # Read-only learning mode

# Learning Objectives
objectives:
  - Map Omarchy OS configuration load order (Hyprland, Waybar, theme system)
  - Detect upstream vs user config divergence safely
  - Analyze configuration structure without modifications
  - Propose merge strategy using conf.d drop-ins
  - Understand Omarchy OS architecture patterns
  - NEVER modify files outside speccy-lab/** (safety rule)

# Prerequisites
prerequisites:
  - Observer stage milestone achieved
  - Basic CLI navigation skills
  - SafeOps guardrails active
  - Omarchy OS environment available

# Training Stages
stages:
  observe:
    desc: 'Observe Omarchy OS configuration structure'
    steps:
      - name: 'Check Omarchy environment paths'
        command: "ls -la ~/.local/share/omarchy ~/.config/omarchy/ 2>/dev/null || echo 'Omarchy dirs not found - using simulation'"
        output: 'speccy-lab/logs/omarchy-dirs.log'
        memory: 'observed Omarchy directory structure - paths identified'
      - name: 'Analyze configuration differences'
        command: "diff -qr ~/.local/share/omarchy ~/.config/omarchy/ 2>/dev/null | head -20 || echo 'No differences found or dirs missing - simulation mode'"
        output: 'speccy-lab/logs/omarchy-diff.log'
        memory: 'observed Omarchy config differences - baseline established'
      - name: 'Map configuration file types'
        command: "find ~/.local/share/omarchy ~/.config/omarchy/ -name '*.conf' -o -name '*.yaml' -o -name '*.json' 2>/dev/null | head -10 | rev | cut -d'/' -f1 | rev | sort | uniq"
        output: 'speccy-lab/logs/omarchy-filetypes.log'
        memory: 'mapped Omarchy configuration file types - structure understood'

  analyse:
    desc: 'Analyze Omarchy configuration patterns'
    steps:
      - name: 'Identify config load order'
        command: "grep -r 'import\\|source\\|include' ~/.local/share/omarchy ~/.config/omarchy/ 2>/dev/null | head -10 || echo 'Config import patterns - simulation results'"
        output: 'speccy-lab/logs/omarchy-imports.log'
        memory: 'analyzed Omarchy config import patterns - load order identified'
      - name: 'Detect theme system structure'
        command: "find ~/.local/share/omarchy ~/.config/omarchy/ -iwholename '*theme*' -o -iwholename '*color*' 2>/dev/null | head -10"
        output: 'speccy-lab/logs/omarchy-themes.log'
        memory: 'analyzed Omarchy theme system - structure mapped'
      - name: 'Check for user customizations'
        command: "find ~/.config/omarchy/ -name '*.user.*' -o -name '*.custom.*' 2>/dev/null || echo 'No custom files found - standard installation'"
        output: 'speccy-lab/logs/omarchy-custom.log'
        memory: 'identified user customizations - divergence points noted'
      - name: 'Reflection on findings'
        command: './speccy reflect'
        memory: 'completed Omarchy configuration analysis - insights captured'

  propose:
    desc: 'Generate safe configuration improvement proposals'
    steps:
      - name: 'Generate configuration proposals'
        command: |
          echo "=== OMARCHY CONFIGURATION ANALYSIS ===" > speccy-lab/logs/omarchy-proposals.log
          echo "Generated: $(date)" >> speccy-lab/logs/omarchy-proposals.log
          echo "Analysis based on configuration structure mapping" >> speccy-lab/logs/omarchy-proposals.log
          echo "" >> speccy-lab/logs/omarchy-proposals.log
          echo "SAFE CONFIGURATION IMPROVEMENTS:" >> speccy-lab/logs/omarchy-proposals.log
          echo "1. Use conf.d drop-ins for divergent configurations" >> speccy-lab/logs/omarchy-proposals.log
          echo "2. Implement theme inheritance system" >> speccy-lab/logs/omarchy-proposals.log
          echo "3. Create configuration validation framework" >> speccy-lab/logs/omarchy-proposals.log
          echo "4. Add backup/restore for custom configurations" >> speccy-lab/logs/omarchy-proposals.log
        memory: 'generated Omarchy configuration improvement proposals - draft-$(date +%F)'
      - name: 'Store Omarchy insights'
        command: "./speccy memory 'OMARCHY_ANALYSIS: configuration structure mapped - 4 improvement proposals identified - $(date +%F)'"
        memory: 'Omarchy configuration analysis stored in memory'
      - name: 'Create configuration ideas log'
        command: "echo 'Omarchy configuration optimization ideas:' > speccy-lab/memory/omarchy-config-ideas.log"
        memory: 'created Omarchy configuration ideas tracking file'

  simulate:
    desc: 'Simulate safe configuration changes'
    steps:
      - name: 'Dry-run configuration merge simulation'
        command: |
          echo "=== SIMULATION: Configuration Merge Strategy ===" > speccy-lab/logs/omarchy-simulation.log
          echo "Simulating conf.d drop-in migration..." >> speccy-lab/logs/omarchy-simulation.log
          DRY=1 ./tools/safe_run.sh "echo 'Testing configuration merge logic'" >> speccy-lab/logs/omarchy-simulation.log 2>&1 || echo "Simulation: configuration merge tested" >> speccy-lab/logs/omarchy-simulation.log
        memory: 'simulated Omarchy configuration merge - safety verified'
      - name: 'Test configuration validation'
        command: 'DRY=1 ./tools/safe_run.sh ''echo "Configuration validation test" | grep -q validation && echo "PASS" || echo "TEST"'''
        output: 'speccy-lab/logs/omarchy-validation.log'
        memory: 'tested configuration validation logic - simulation complete'
      - name: 'Validate read-only boundaries'
        command: "echo 'Read-only test: $(pwd)' | grep -q speccy-lab && echo 'PASS: Read-only boundary confirmed' || echo 'INFO: Working outside lab - simulation mode'"
        memory: 'validated read-only learning boundaries - safety confirmed'

  report:
    desc: 'Generate Omarchy lesson completion report'
    steps:
      - name: 'Generate completion report'
        command: |
          echo "=== OMARCHY READ-ONLY LESSON REPORT ===" > speccy-lab/logs/omarchy-report.log
          echo "Date: $(date)" >> speccy-lab/logs/omarchy-report.log
          echo "Stage: observer (read-only)" >> speccy-lab/logs/omarchy-report.log
          echo "Status: SUCCESS" >> speccy-lab/logs/omarchy-report.log
          echo "" >> speccy-lab/logs/omarchy-report.log
          echo "OMARCHY INSIGHTS GAINED:" >> speccy-lab/logs/omarchy-report.log
          echo "✅ Configuration structure mapped" >> speccy-lab/logs/omarchy-report.log
          echo "✅ Load order patterns identified" >> speccy-lab/logs/omarchy-report.log
          echo "✅ Theme system analyzed" >> speccy-lab/logs/omarchy-report.log
          echo "✅ Safe improvement proposals generated" >> speccy-lab/logs/omarchy-report.log
          echo "✅ Configuration simulation completed" >> speccy-lab/logs/omarchy-report.log
          echo "" >> speccy-lab/logs/omarchy-report.log
          echo "NEXT STEPS:" >> speccy-lab/logs/omarchy-report.log
          echo "1. Review configuration proposals" >> speccy-lab/logs/omarchy-report.log
          echo "2. Test conf.d drop-in implementation" >> speccy-lab/logs/omarchy-report.log
          echo "3. Validate theme inheritance system" >> speccy-lab/logs/omarchy-report.log
        memory: 'omarchy_readonly_lesson_complete - report generated'
      - name: 'Store lesson completion'
        command: "./speccy memory 'milestone_achieved: omarchy_readonly_lesson_complete - configuration expert level 1'"
        memory: 'Omarchy lesson milestone stored in memory'
      - name: 'Final reflection'
        command: './speccy reflect'
        memory: 'final Omarchy lesson reflection completed - objectives achieved'

# Success Criteria
success_criteria:
  - All stages completed without errors
  - At least 2 memory entries created
  - Configuration analysis completed
  - Improvement proposals generated
  - Read-only boundaries maintained
  - No modifications to system files
  - Omarchy structure understanding demonstrated

# Safety Rules (enforced by SafeOps)
safety_rules:
  - 'Never modify files outside speccy-lab/'
  - 'Always use DRY=1 for simulations'
  - 'Read-only access to system configurations'
  - 'Store all insights in memory system'
  - 'Maintain SafeOps compliance'
  - 'Never alter Omarchy OS functionality'

# Learning Outcomes
learning_outcomes:
  - AI understands Omarchy OS configuration architecture
  - Identifies configuration patterns and load order
  - Generates safe improvement proposals
  - Practices read-only system analysis
  - Builds foundation for configuration management
  - Develops expertise in desktop environment structure

# Next Lesson Readiness
next_lesson_readiness:
  - lesson_name: 'Task-Chain Automation'
  - prerequisites:
      - 'Observer stage milestone achieved'
      - 'Omarchy configuration analysis complete'
      - 'SafeOps read-only compliance confirmed'
  - trigger: 'When AI demonstrates safe configuration understanding'
