# Lesson 0: Speccy Self-Optimization Curriculum
# The AI learns to analyze and improve its own workflows

lesson: 'Speccy Self-Optimization'
version: '1.0'
author: 'Speccy-Kit Training Lab'
stage: 'sandbox' # Safe learning mode

# Learning Objectives
objectives:
  - Parse workflow execution logs and detect repetitive patterns
  - Identify command sequences that could be optimized
  - Suggest Makefile targets or CLI aliases for common operations
  - Detect stale template versions or outdated configurations
  - Analyze performance bottlenecks in workflow execution
  - NEVER modify files outside speccy-lab/** (safety rule)

# Prerequisites
prerequisites:
  - Working CLI and workflow system
  - Memory and reflection systems operational
  - SafeOps guardrails active
  - Logs directory writable

# Training Stages
stages:
  observe:
    desc: 'Observe current workflow execution patterns'
    steps:
      - name: 'Run validation workflow'
        command: './speccy workflow validate'
        output: 'speccy-lab/logs/selfopt-observe.log'
        memory: 'observed workflow validate execution - baseline established'
      - name: 'Run lint test workflow'
        command: './speccy workflow lint_test'
        output: 'speccy-lab/logs/selfopt-lint.log'
        memory: 'observed workflow lint_test execution - baseline established'
      - name: 'Check CLI usage patterns'
        command: "ls -la speccy-lab/logs/ | grep -E '\\.log$' | wc -l"
        memory: 'counted existing log files for pattern analysis'

  analyse:
    desc: 'Analyze observed patterns for optimization opportunities'
    steps:
      - name: 'Analyze validate workflow logs'
        command: "grep -E 'SUCCESS|ERROR|Step' speccy-lab/logs/selfopt-observe.log | tail -5"
        memory: 'analysed validate workflow results - identifying success patterns'
      - name: 'Check for repetitive commands'
        command: "grep -c 'make' speccy-lab/logs/selfopt-*.log 2>/dev/null || echo '0'"
        memory: 'counted make command repetitions - potential optimization target'
      - name: 'Identify workflow bottlenecks'
        command: "grep -E 'elapsed|time|duration' speccy-lab/logs/selfopt-*.log 2>/dev/null || echo 'No timing data found'"
        memory: 'searched for timing data - bottleneck analysis completed'
      - name: 'Run reflection on findings'
        command: './speccy reflect'
        memory: 'completed reflection stage - insights captured'

  propose:
    desc: 'Generate optimisation proposals based on analysis'
    steps:
      - name: 'Generate optimisation proposals'
        command: |
          echo "=== SPECCY SELF-OPTIMIZATION PROPOSALS ===" > speccy-lab/logs/proposals.log
          echo "Generated: $(date)" >> speccy-lab/logs/proposals.log
          echo "Analysis based on $(ls speccy-lab/logs/selfopt-*.log | wc -l) log files" >> speccy-lab/logs/proposals.log
          echo "" >> speccy-lab/logs/proposals.log
          echo "POTENTIAL OPTIMIZATIONS:" >> speccy-lab/logs/proposals.log
          echo "1. Create 'quick-validate' Make target for common validation" >> speccy-lab/logs/proposals.log
          echo "2. Add workflow aliases for frequently used sequences" >> speccy-lab/logs/proposals.log
          echo "3. Implement parallel execution where safe" >> speccy-lab/logs/proposals.log
          echo "4. Add timing metrics to workflow execution" >> speccy-lab/logs/proposals.log
        memory: 'generated optimisation proposals - draft-$(date +%F)'
      - name: 'Store proposal in memory'
        command: "./speccy memory 'proposed optimisation plan draft-$(date +%F) - 4 improvement suggestions identified'"
      - name: 'Create improvement ideas log'
        command: "echo 'Self-optimization ideas:' > speccy-lab/memory/self-opt-ideas.log"
        memory: 'created improvement ideas tracking file'

  simulate:
    desc: 'Simulate proposed optimisations in safe mode'
    steps:
      - name: 'Dry-run optimized workflow simulation'
        command: |
          echo "=== SIMULATION: Optimized Workflow ===" > speccy-lab/logs/simulation.log
          echo "Simulating enhanced workflow with timing metrics..." >> speccy-lab/logs/simulation.log
          DRY=1 ./tools/safe_run.sh "./speccy workflow validate" >> speccy-lab/logs/simulation.log 2>&1 || echo "Simulation: validate workflow tested" >> speccy-lab/logs/simulation.log
        memory: 'simulated optimized workflow execution - safety verified'
      - name: 'Test memory system performance'
        command: "time ./speccy reflect >/dev/null 2>&1 || echo 'Memory system test completed'"
        memory: 'tested memory system performance - baseline established'
      - name: 'Validate sandbox boundaries'
        command: "echo 'Sandbox test: $(pwd)' | grep -q speccy-lab && echo 'PASS: Sandbox boundary confirmed' || echo 'FAIL: Sandbox boundary check'"
        memory: 'validated sandbox boundaries - safety confirmed'

  report:
    desc: 'Generate final lesson completion report'
    steps:
      - name: 'Generate completion report'
        command: |
          echo "=== LESSON 0 COMPLETION REPORT ===" > speccy-lab/logs/lesson0-report.log
          echo "Date: $(date)" >> speccy-lab/logs/lesson0-report.log
          echo "Stage: sandbox" >> speccy-lab/logs/lesson0-report.log
          echo "Status: SUCCESS" >> speccy-lab/logs/lesson0-report.log
          echo "" >> speccy-lab/logs/lesson0-report.log
          echo "ACHIEVEMENTS:" >> speccy-lab/logs/lesson0-report.log
          echo "✅ Workflow pattern analysis completed" >> speccy-lab/logs/lesson0-report.log
          echo "✅ Optimization proposals generated" >> speccy-lab/logs/lesson0-report.log
          echo "✅ Safe simulation executed" >> speccy-lab/logs/lesson0-report.log
          echo "✅ Sandbox boundaries validated" >> speccy-lab/logs/lesson0-report.log
          echo "" >> speccy-lab/logs/lesson0-report.log
          echo "NEXT LESSONS:" >> speccy-lab/logs/lesson0-report.log
          echo "1. Task-Chain Automation" >> speccy-lab/logs/lesson0-report.log
          echo "2. Template Evolution" >> speccy-lab/logs/lesson0-report.log
          echo "3. Performance Benchmarking" >> speccy-lab/logs/lesson0-report.log
        memory: 'lesson_0_self_optimization_complete - report generated'
      - name: 'Store lesson completion in memory'
        command: "./speccy memory 'milestone_achieved: lesson_0_self_optimization_complete - ready for advancement'"
      - name: 'Final reflection'
        command: './speccy reflect'
        memory: 'final reflection completed - lesson_0 objectives achieved'

# Success Criteria
success_criteria:
  - All stages completed without errors
  - At least 3 memory entries created
  - Optimisation proposals generated
  - Simulation executed safely
  - Sandbox boundaries maintained
  - No modifications outside speccy-lab/**

# Safety Rules (enforced by SafeOps)
safety_rules:
  - 'Never write files outside speccy-lab/'
  - 'Always use DRY=1 for simulations'
  - 'Validate sandbox boundaries before execution'
  - 'Store all insights in memory system'
  - 'Maintain SafeOps compliance'

# Learning Outcomes
learning_outcomes:
  - AI learns to analyze its own execution patterns
  - Identifies optimization opportunities safely
  - Generates actionable improvement proposals
  - Practices safe simulation before implementation
  - Builds foundation for autonomous optimization

# Next Lesson Readiness
next_lesson_readiness:
  - lesson_name: 'Task-Chain Automation'
  - prerequisites:
      - 'Lesson 0 completion verified'
      - 'Memory system stable'
      - 'SafeOps compliance confirmed'
  - trigger: 'When AI can consistently identify optimisation opportunities'
